server:
    port: 8082
    context-path: /

spring:
    application:
        name: ai
    ai:
        zhipuai:
            api-key: 70fe63917349444c9007fb9de011f202.pyN7J0lgdpDBvB3r
            base-url:  https://open.bigmodel.cn/api/paas
            embedding:
                options:
                    model: embedding-2
            chat:
                options:
                    model: GLM-4-Flash