server:
    port: 8082
    context-path: /

spring:
    application:
        name: ai
    ai:
        deepseek:
            api-key: ${DEEPSEEK_API_KEY}
            base-url: https://api.openai-proxy.org/v1/chat/completions
            chat:
                options:
                    model: deepseek-chat
                    temperature: 0.8