server:
    port: 8081
    context-path: /ai

spring:
    application:
        name: ai
    ai:
        openai:
            api-key: ${OPENAI_API_KEY}
            base-url: https://dashscope.aliyuncs.com/compatible-mode
            chat:
                options:
                    model: qwen-plus