server:
    port: 8082


spring:
    ai:
        zhipuai:
            api-key: ${ZHIPUAI_API_KEY}
            chat:
                options:
                    model: glm-4-plus
        mcp:
            client:
                enabled: true
                request-timeout: 30s
                stdio:
                    servers:
                        mcp-server:
                            command: java
                            args:
                                - "-Dfile.encoding=UTF-8"
                                - "-jar"
                                - "E:\\mywork\\kcnf-open\\spring-ai-sample\\spring-ai\\spring-ai-sample10-mcp-server\\target\\spring-ai-sample10-mcp-server-v1.jar"
                            working-directory: "E:\\mywork\\kcnf-open\\spring-ai-sample\\spring-ai\\spring-ai-sample10-mcp-server\\target"

logging:
    level:
        root: WARN
        com.kcnf.ai: INFO
        org.springframework.ai.mcp: DEBUG
        io.modelcontextprotocol: DEBUG
