server:
    port: 8082
    context-path: /


spring:
    ai:
        zhipuai:
            api-key: ${ZHIPUAI_API_KEY}
            chat:
                options:
                    model: glm-4-plus
        mcp:
            client:
                # 通用客户端配置
                enabled: true                # 是否启用 MCP 客户端，默认为 true
                name: my-mcp-client          # 客户端名称
                version: 1.0.0               # 客户端版本
                type: SYNC                   # 客户端类型，可选 SYNC 或 ASYNC
                request-timeout: 30s         # 请求超时时间，默认为 20s
                # stdio 传输配置
                stdio:
                    # 方式二：引用外部JSON文件（Claude Desktop风格）
                    servers-configuration: classpath:mcp-servers.json

logging:
    level:
        root: INFO
        org.springframework.ai.mcp: DEBUG
        com.kcnf.ai: DEBUG